### ISSUE TITLE
Allow to define section or/and body without the need to render it

### ISSUE THREAD

**Issue by danilodeven** [aspnet/Mvc#3293]
It would be nice if we could just prevent the render of the `body` or/and the `section` like this without get the exception:
```c#
@if (someLogicIsFalseHere) {
    RenderSection("adminMenu");
}
```
###### `InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'adminMenu'.`

I use the "section" to make various versions of the views using the same "layout.cshtml" for different browsers, users, permissions and requests types with the same controller and model.

The way I current make this in asp.net 4.5 is like the code bellow, but this workaround doesn't work properly in asp.net 5 beta 7. This was discussed in the issue https://github.com/aspnet/Mvc/issues/3283
```c#
@if (someLogicIsFalseHere) {
    WriteTo(TextWriter.Null, RenderBody());
    WriteTo(TextWriter.Null, RenderSection("adminMenu"));
    RenderSection("alternativeMenu");
}
```

**Comment by Eilon** [comment]
This issue requires just a bit of design. We're happy to collaborate with folks on how this could be implemented.

**Comment by pranavkm** [comment]
Does it execute the body at all? Or is the rendering the only thing that's supressed?

**Comment by danilodeven** [comment]
This is giving the error just when the logic doesn't call the `@RenderSection("adminSection")` and works fine when it doesn't call the `@RenderBody()`. (the `@RenderBody` need to appears somewhere in the `Layout.cshtml` file at-list once.)
Appears that if suppress the obligation to render the defined sections would do the trick. The `@RenderSection()` should work like the `@RenderBody()`.

Bellow all the code I used to test:

`Home/Index.cshtml`
```html
@{
	Layout = "_Layout";
	ViewData["Title"] = "Home Page";
}
@section adminSection {
	<div>
		<p>You are administrator. Take some action:</p>
		<p>
			<button id="action1">See the new registers</button>
			<button id="action2">Do something else</button>
		</p>
	</div>
}
<div>
	<p>Welcome new user. Register your self</p>
	<form method="POST">
		<input name="fullName"/>
		<input name="email"/>
		<input type="submit"/>
	</form>
</div>
```
`Shared/_Layout.cshtml`
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebApplicationTeste</title>
</head>
<body>
	@{
		// simple logic result test:
		bool isAdmin = false;
	}
	<div>
		<div>Comom layout here</div>
		<div class="content">
			@if (isAdmin) {
				<div>Admin layout <a href="#">sign out</a></div>
				<div>
					@RenderSection("adminSection", required: false)
					<!-- No RenderBody() in this case: WORKS FINE  -->
				</div>
			} else {
				<div>normal layout</div>
				<div>
					@RenderBody()
					<!-- NO RenderSection("adminSection") in this case: GIVE ERROR -->
				</div>
			}
		</div>
		<div>comom bottom here</div>
	</div>
</body>
</html>

```

### when the `isAdmin` is `false` give the error:
##### An unhandled exception occurred while processing the request.
###### InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'adminSection'.

### when the `isAdmin` is `true` works fine:
##### `output` when `isAdmin` is `true`:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>Home Page - WebApplicationTeste</title>
</head>
<body>

	<div>
		<div>Common layout here</div>
		<div class="content">
			<div>Admin layout <a href="#">sign out</a></div>
			<div>

				<div>
					<p>You are administrator. Take some action:</p>
					<p>
						<button id="action1">See the new registers</button>
						<button id="action2">Do something else</button>
					</p>
				</div>

				<!-- No RenderBody() in this case: WORKS FINE  -->
			</div>
		</div>
		<div>common bottom here</div>
	</div>
</body>
</html>
```

**Comment by danilodeven** [comment]
Can just remove these lines?
https://github.com/aspnet/Mvc/blob/f57e1809716c4c99d7cf6e444594e51e495e6513/src/Microsoft.AspNet.Mvc.Razor/RazorView.cs#L223-L227

**Comment by Eilon** [comment]
@danilodeven I don't want to remove those lines, but changing that method to have more conditional logic in it is I think the thing to do. The current behavior is important in order to alert a developer of *inadvertently* forgetting to render a section or the body.

But for more advanced scenarios I'm imagining adding functionality to suppress these errors. For example, we could add some new methods to the RazorPage base class:

```c#
void IgnoreUnrenderedSection(string sectionName); // suppresses errors about unrendered section 'sectionName'
void IgnoreUnrenderedBody(); // suppresses errors about not calling RenderBody()
```

These methods would set some flags on the page (or somewhere). Then when `EnsureRenderedBodyOrSections` is called, it would look at these flags to decide whether to actually throw an error.

**Comment by danilodeven** [comment]
This will be great. Thank you @Eilon

**Comment by Eilon** [comment]
@danilodeven we moved this to our backlog because it hasn't been a very common piece of feedback. But we're open to accepting a contribution on this if you're interested.

**Comment by dougbu** [comment]
@Eilon, @danilodeven should encounter an error when `IsAdmin` is `true` as well: The body is defined but not rendered. Suspect `EnsureRenderedBodyOrSections()` only checks the status of the body if no sections are defined at all. Probably don't want to fix that (and make @danilodeven's workaround worse) until we have `IgnoreUnrenderedBody()` or similar.

**Comment by Eilon** [comment]
Right, it should already be the case that the body isn't required if at least one section is rendered. But not sure how my previous statements wouldn't remain true, though. My recommendation is an all-or-none deal, not piecemeal.

**Comment by dougbu** [comment]
Agreed. I wasn't saying anything above was `false`.

**Comment by danilodeven** [comment]
@Eilon @dougbu I just clone the mvc repository and I will be more than happy to help with this implementation.

**Comment by Eilon** [comment]
@danilodeven if you'd like to send a "Design PR" with what the APIs would look like, we will take a look and work with you on fine-tuning it.

**Comment by danilodeven** [comment]
@Eilon I couldn't put together the dependencies to work in the `MVC`, not even the samples of the solution I cloned. Doesn't build. I will try to figure out what's wrong. 
In the meanwhile if somebody else would like to grab this one it's ok.

I think we should make the methods to ignore the render with a shorter and simpler name like this ones:
```c#
void IgnorerBody()
void IgnoreSection(string sectionName)
```
And we can use the method to be called when it convenient inside the conditional logic like bellow: 

#### Use like this: 
```c#
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationTeste</title>
</head>
<body>
    @{
        // simple logic result test:
        bool isAdmin = false;
    }
    <div>
        <div>Comom layout here</div>
        <div class="content">
            @if (isAdmin) {
                <div>Admin layout <a href="#">sign out</a></div>
                <div>
                    @RenderSection("adminSection")
                    @IgnoreBody()
                </div>
            } else {
                <div>normal layout</div>
                <div>
                    @IgnoreSection("adminSection")
                    @RenderBody()
                </div>
            }
        </div>
        <div>comom bottom here</div>
    </div>
</body>
</html>
```
This way the method call stay inside the 'scope' preventing the `IgnorerBody()` or `IgnoreSection('sectionName')` to be unnoticed on the top and the Render ignored unintentionally without exception.
Then we should put a tip in the exception: 
##### An unhandled exception occurred while processing the request.
InvalidOperationException: The following sections have been defined but have not been rendered by the page at '/Views/Shared/_Layout.cshtml': 'adminSection'. `If it was intentional please use the method IgnoreSection("adminSection")`.

**Comment by Eilon** [comment]
@danilodeven thanks, I like the design, very helpful. This is currently on our Backlog so it's unlikely to make it into the current version, but will certainly be reconsidered at a later time.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Mvc/commit/1e5b0b9becab1e6ba2a4978df880d74fba234439

**Comment by ggirard07** [comment]
I don't understand how `@IgnoreBody()` is intended to be used.
In ASP.Net Core 2 It returns `void` which seems to not be supported in a Razor layout where at least a return type of `object` is expected: 

> cannot convert from 'void' to 'object'

**Comment by dougbu** [comment]
> I don't understand how `@IgnoreBody()` is intended to be used.

Use `@{ IgnoreBody(); }` instead. I updated the earlier example to fix this typo.

**Comment by ggirard07** [comment]
@dougbu thanks for the clarification.
But it looks like I am still missing something...

> An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

My template is currently defined as follow
```html
<!DOCTYPE html>
<html>

<head>
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8">
    <meta name="generator" content="My App">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <div id="page" class="nofouc">
        <div id="panel-body">
            <div id="title">@ViewData["Title"]</div>
            @{ IgnoreBody(); }
            <div id="api">
            </div>
        </div>
    </div>

    @{ IgnoreSection("Scripts"); }
</body>

</html>
```

**Comment by dougbu** [comment]
@ggirard07 we're straying far from the issue discussed in this thread. Missing dependencies is covered in other issues in this repo as well as in https://github.com/aspnet/Home I also suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the 'asp.net-core-mvc' [tag](https://stackoverflow.com/questions/tagged/asp.net-core-mvc).
